# Generated by Django 5.1.15 on 2026-09-15 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('content', models.TextField(help_text='Markdown', verbose_name='conteúdo')),
                ('views', models.PositiveIntegerField(default=0)),
                ('helpful_votes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='tickets.category')),
            ],
            options={
                'verbose_name': 'artigo',
                'verbose_name_plural': 'artigos',
                'ordering': ['-created_at'],
            },
        ),
    ]
