# Generated by Django 5.1.15 on 2026-09-15 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30, unique=True, verbose_name='tag de patrimônio')),
                ('type', models.CharField(choices=[('NOTEBOOK', 'Notebook'), ('DESKTOP', 'Desktop'), ('MONITOR', 'Monitor'), ('PERIFERICO', 'Periférico'), ('CELULAR', 'Celular')], max_length=20, verbose_name='tipo')),
                ('brand_model', models.CharField(max_length=150, verbose_name='marca/modelo')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='número de série')),
                ('status', models.CharField(choices=[('EM_USO', 'Em uso'), ('ESTOQUE', 'Estoque'), ('MANUTENCAO', 'Manutenção'), ('DESCARTADO', 'Descartado')], default='ESTOQUE', max_length=20)),
                ('purchased_at', models.DateField(blank=True, null=True, verbose_name='data de compra')),
                ('warranty_until', models.DateField(blank=True, null=True, verbose_name='fim da garantia')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ativo',
                'verbose_name_plural': 'ativos',
                'ordering': ['tag'],
            },
        ),
    ]
