# Generated by Django 5.1.15 on 2026-09-15 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], unique=True, verbose_name='dia da semana')),
                ('start_time', models.TimeField(verbose_name='início')),
                ('end_time', models.TimeField(verbose_name='fim')),
            ],
            options={
                'verbose_name': 'horário comercial',
                'verbose_name_plural': 'horários comerciais',
                'ordering': ['weekday'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='data')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'feriado',
                'verbose_name_plural': 'feriados',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='SLAPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], max_length=10, unique=True, verbose_name='prioridade')),
                ('first_response_minutes', models.PositiveIntegerField(verbose_name='prazo de 1ª resposta (minutos úteis)')),
                ('resolution_minutes', models.PositiveIntegerField(verbose_name='prazo de resolução (minutos úteis)')),
            ],
            options={
                'verbose_name': 'política de SLA',
                'verbose_name_plural': 'políticas de SLA',
                'ordering': ['first_response_minutes'],
            },
        ),
        migrations.CreateModel(
            name='Macro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='título')),
                ('body_template', models.TextField(help_text='Use {{usuario}}, {{chamado}} e {{agente}} como variáveis.', verbose_name='texto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'macro',
                'verbose_name_plural': 'macros',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readable_id', models.CharField(blank=True, editable=False, max_length=12, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('description', models.TextField(verbose_name='descrição')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANDAMENTO', 'Em andamento'), ('AGUARDANDO_RESPOSTA', 'Aguardando resposta'), ('RESOLVIDO', 'Resolvido'), ('FECHADO', 'Fechado'), ('REABERTO', 'Reaberto')], default='ABERTO', max_length=20)),
                ('priority', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=10)),
                ('support_level', models.CharField(choices=[('N1', 'N1'), ('N2', 'N2')], default='N1', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_response_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_atribuidos', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.category')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_abertos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'chamado',
                'verbose_name_plural': 'chamados',
                'ordering': ['-created_at'],
            },
        ),
    ]
